"""``marvi presence`` -- setup/status/pause/resume for Marvi's presence
subsystem (Workstream B of the subconscious+presence design).

Self-contained module: builds its own argparse subparser and dispatches
internally (mirrors ``runtime_support/portal_cli.py``), so wiring it into
``runtime_support/main.py`` is two lines (import + ``add_parser(subparsers)``).

Subcommands:
  setup    -- probe ActivityWatch, start the media watcher (Windows-only,
              supervised background process), and create/refresh the
              presence distiller cron job.
  status   -- AW reachable? watcher running? distiller job present?
  pause    -- stop the watcher and set presence.enabled: false.
  resume   -- start the watcher and set presence.enabled: true.
"""

from __future__ import annotations

import json
import platform
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

from runtime_support.colors import Colors, color

ACTIVITYWATCH_DOWNLOAD_URL = "https://activitywatch.net/downloads/"

DISTILL_JOB_NAME = "presence-distiller"
DISTILL_SCRIPT_NAME = "presence_distill.py"
DISTILL_DEFAULT_SCHEDULE = "0 3 * * *"

_DISTILL_SCRIPT_TEMPLATE = '''"""Auto-generated by `marvi presence setup` -- safe to regenerate, do not
hand-edit (re-run `marvi presence setup` to refresh it).

Prints an ActivityWatch presence digest to stdout for the presence
distiller cron job -- `cron/scheduler.py` injects a script's stdout into
the agent's prompt for that run -- and records this run's timestamp.
"""
import sys

# Resolved at generation time: the cron scheduler runs this script as a
# bare subprocess (`sys.executable <script>`, no inherited sys.path), so a
# source-checkout install needs the project root added explicitly. This is
# a harmless no-op for pip installs, where the `tools` package is already
# importable from site-packages. Mirrors the bootstrap in
# cron/scripts/subconscious_snapshot.py.
_PROJECT_ROOT = {project_root!r}
if _PROJECT_ROOT and _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from tools.presence.distill import print_digest_for_cron

if __name__ == "__main__":
    print_digest_for_cron()
'''


# ---------------------------------------------------------------------------
# Config helpers
# ---------------------------------------------------------------------------


def _set_presence_enabled(enabled: bool) -> None:
    from runtime_support.config import load_config, save_config

    cfg = load_config()
    section = cfg.get("presence")
    if not isinstance(section, dict):
        section = {}
    section["enabled"] = bool(enabled)
    cfg["presence"] = section
    save_config(cfg)


def _distill_schedule() -> str:
    from tools.presence.common import get_presence_config

    schedule = get_presence_config().get("distill_schedule")
    return str(schedule) if schedule else DISTILL_DEFAULT_SCHEDULE


# ---------------------------------------------------------------------------
# Media watcher process supervision
# ---------------------------------------------------------------------------


def _presence_dir() -> Path:
    from runtime_support.config import get_marvi_home

    d = get_marvi_home() / "presence"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _watcher_state_path() -> Path:
    return _presence_dir() / "media_watcher.json"


def _read_watcher_state() -> Optional[Dict[str, Any]]:
    try:
        return json.loads(_watcher_state_path().read_text(encoding="utf-8"))
    except Exception:
        return None


def _write_watcher_state(pid: int, start_time: Optional[int]) -> None:
    try:
        _watcher_state_path().write_text(
            json.dumps({"pid": pid, "start_time": start_time}), encoding="utf-8",
        )
    except OSError:
        pass


def _clear_watcher_state() -> None:
    try:
        _watcher_state_path().unlink(missing_ok=True)
    except OSError:
        pass


def _watcher_pid_alive(state: Dict[str, Any]) -> bool:
    from gateway.status import _pid_exists, get_process_start_time

    pid = state.get("pid")
    if not pid:
        return False
    if not _pid_exists(int(pid)):
        return False
    expected_start = state.get("start_time")
    if expected_start is None:
        return True
    return get_process_start_time(int(pid)) == expected_start


def watcher_pid_if_running() -> Optional[int]:
    """Return the media watcher's PID if the tracked process is alive."""
    state = _read_watcher_state()
    if not state or not _watcher_pid_alive(state):
        return None
    return int(state["pid"])


def start_watcher() -> Tuple[bool, str]:
    """Spawn the media watcher as a detached background process.

    Reuses the repo's Windows-detach convention (runtime_support._subprocess_compat
    .windows_detach_flags, the same helper the gateway's own background
    watchers use) rather than inventing a second supervision mechanism.
    """
    if platform.system() != "Windows":
        return False, "media watcher is Windows-only (SMTC); skipped on this platform"

    existing_pid = watcher_pid_if_running()
    if existing_pid:
        return True, f"media watcher already running (pid {existing_pid})"

    from runtime_support._subprocess_compat import windows_detach_flags
    from gateway.status import get_process_start_time

    log_path = _presence_dir() / "media_watcher.log"
    try:
        log_file = open(log_path, "a", encoding="utf-8")
    except OSError:
        log_file = subprocess.DEVNULL

    try:
        proc = subprocess.Popen(
            [sys.executable, "-m", "tools.presence.media_watcher"],
            stdout=log_file,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            creationflags=windows_detach_flags(),
            close_fds=True,
        )
    except OSError as exc:
        return False, f"failed to start media watcher: {exc}"

    start_time = get_process_start_time(proc.pid)
    _write_watcher_state(proc.pid, start_time)
    return True, f"media watcher started (pid {proc.pid})"


def stop_watcher() -> Tuple[bool, str]:
    pid = watcher_pid_if_running()
    if not pid:
        _clear_watcher_state()
        return True, "media watcher was not running"

    from gateway.status import terminate_pid

    try:
        terminate_pid(pid, force=True)
    except Exception as exc:
        return False, f"failed to stop media watcher (pid {pid}): {exc}"
    _clear_watcher_state()
    return True, f"media watcher stopped (pid {pid})"


# ---------------------------------------------------------------------------
# Distiller cron job
# ---------------------------------------------------------------------------


def _project_root() -> str:
    """The directory that makes ``tools.presence.distill`` importable.

    Empty string when the package layout is unexpected (the generated
    script's bootstrap then no-ops and relies on a normal pip install).
    """
    try:
        import tools.presence.distill as _distill_mod

        # .../<root>/tools/presence/distill.py -> <root>
        return str(Path(_distill_mod.__file__).resolve().parents[2])
    except Exception:
        return ""


def _write_distill_script() -> Path:
    from runtime_support.config import get_marvi_home

    scripts_dir = get_marvi_home() / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    path = scripts_dir / DISTILL_SCRIPT_NAME
    path.write_text(
        _DISTILL_SCRIPT_TEMPLATE.format(project_root=_project_root()),
        encoding="utf-8",
    )
    return path


def _find_distill_job() -> Optional[Dict[str, Any]]:
    from cron.jobs import list_jobs

    for job in list_jobs(include_disabled=True):
        if job.get("name") == DISTILL_JOB_NAME:
            return job
    return None


def ensure_distill_job(schedule: Optional[str] = None) -> Tuple[bool, str]:
    """Create the presence distiller cron job if missing, or refresh its
    schedule if ``presence.distill_schedule`` changed. Idempotent."""
    schedule = schedule or _distill_schedule()
    _write_distill_script()

    existing = _find_distill_job()
    if existing:
        if existing.get("state") == "paused" or existing.get("enabled") is False:
            try:
                from cron.jobs import resume_job

                existing = resume_job(existing["id"]) or existing
            except Exception as exc:
                return False, f"presence distiller job resume failed: {exc}"
        updates: Dict[str, Any] = {}
        if existing.get("schedule_display") != schedule:
            updates["schedule"] = schedule
        if existing.get("enabled_toolsets") != ["memory"]:
            updates["enabled_toolsets"] = ["memory"]
        if updates:
            try:
                from cron.jobs import update_job

                update_job(existing["id"], updates)
            except Exception as exc:
                return False, f"presence distiller job update failed: {exc}"
            return True, f"presence distiller job updated (id={existing['id']}, schedule={schedule})"
        return True, f"presence distiller job already up to date (id={existing['id']})"

    from tools.presence.distill import DISTILL_SYSTEM_NOTE

    try:
        from cron.jobs import create_job

        job = create_job(
            prompt=DISTILL_SYSTEM_NOTE,
            schedule=schedule,
            name=DISTILL_JOB_NAME,
            script=DISTILL_SCRIPT_NAME,
            deliver="local",
            enabled_toolsets=["memory"],
        )
    except Exception as exc:
        return False, f"failed to create presence distiller job: {exc}"
    return True, f"presence distiller job created (id={job.get('id')}, schedule={schedule})"


def pause_distill_job() -> Tuple[bool, str]:
    job = _find_distill_job()
    if not job:
        return True, "presence distiller job was not configured"
    try:
        from cron.jobs import pause_job

        pause_job(job["id"], reason="presence paused")
    except Exception as exc:
        return False, f"failed to pause presence distiller: {exc}"
    return True, f"presence distiller paused (id={job['id']})"


# ---------------------------------------------------------------------------
# Subcommand handlers
# ---------------------------------------------------------------------------


def _print_line(ok: bool, message: str) -> None:
    mark = color("✓", Colors.GREEN) if ok else color("✗", Colors.RED)
    print(f"  {mark} {message}")


def setup_presence() -> Dict[str, Any]:
    """Probe ActivityWatch, start the media watcher, ensure the presence
    distiller cron job, and set ``presence.enabled: true``.

    Single source of truth for both ``marvi presence setup`` and
    ``POST /api/presence/setup`` (runtime_support/web_server.py) -- the CLI
    handler below only formats this dict for terminal output.
    """
    from tools.presence.aw_client import aw_client

    aw_ok = aw_client.is_available()
    watcher_ok, watcher_msg = start_watcher()
    schedule = _distill_schedule()
    job_ok, job_msg = ensure_distill_job(schedule)
    _set_presence_enabled(True)

    return {
        "activitywatch_available": aw_ok,
        "watcher_ok": watcher_ok,
        "watcher_message": watcher_msg,
        "job_ok": job_ok,
        "job_message": job_msg,
        "enabled": True,
    }


def get_presence_status() -> Dict[str, Any]:
    """Return presence config, ActivityWatch reachability, media-watcher
    state, and the distiller cron job's live state.

    Single source of truth for both ``marvi presence status`` and
    ``GET /api/presence/status``.
    """
    from tools.presence.common import get_presence_config
    from tools.presence.aw_client import aw_client

    return {
        "config": get_presence_config(),
        "activitywatch_reachable": aw_client.is_available(),
        "is_windows": platform.system() == "Windows",
        "watcher_pid": watcher_pid_if_running(),
        "distill_job": _find_distill_job(),
    }


def pause_presence() -> Dict[str, Any]:
    """Stop the media watcher and set ``presence.enabled: false``.

    Single source of truth for both ``marvi presence pause`` and
    ``POST /api/presence/pause``.
    """
    watcher_ok, watcher_msg = stop_watcher()
    job_ok, job_msg = pause_distill_job()
    _set_presence_enabled(False)
    return {
        "ok": watcher_ok and job_ok,
        "message": f"{watcher_msg}; {job_msg}",
        "enabled": False,
        "watcher_ok": watcher_ok,
        "job_ok": job_ok,
    }


def resume_presence() -> Dict[str, Any]:
    """Start the media watcher and set ``presence.enabled: true``.

    Single source of truth for both ``marvi presence resume`` and
    ``POST /api/presence/resume``.
    """
    watcher_ok, watcher_msg = start_watcher()
    job_ok, job_msg = ensure_distill_job()
    _set_presence_enabled(True)
    return {
        "ok": watcher_ok and job_ok,
        "message": f"{watcher_msg}; {job_msg}",
        "enabled": True,
        "watcher_ok": watcher_ok,
        "job_ok": job_ok,
    }


def _cmd_setup(args) -> int:
    print()
    print(color("  Marvi Presence Setup", Colors.MAGENTA))
    print(color("  ─────────────────────", Colors.MAGENTA))

    result = setup_presence()

    if result["activitywatch_available"]:
        _print_line(True, "ActivityWatch is running (http://localhost:5600)")
    else:
        _print_line(False, "ActivityWatch not detected at http://localhost:5600")
        print(
            f"    Install it from {ACTIVITYWATCH_DOWNLOAD_URL} and start it, "
            "then run `marvi presence setup` again (or `marvi presence "
            "status` to re-check). Marvi's presence features degrade "
            "gracefully without it -- nothing else in this setup depends "
            "on it succeeding right now."
        )

    _print_line(result["watcher_ok"], result["watcher_message"])
    _print_line(result["job_ok"], result["job_message"])

    _print_line(True, "presence.enabled set to true")

    print()
    return 0


def _cmd_status(args) -> int:
    print()
    print(color("  Marvi Presence Status", Colors.MAGENTA))
    print(color("  ──────────────────────", Colors.MAGENTA))

    status = get_presence_status()
    cfg = status["config"]

    print(f"  presence.enabled:      {cfg.get('enabled')}")
    print(f"  presence.flow_gating:  {cfg.get('flow_gating')}")
    goblin = cfg.get("goblin", {})
    print(f"  goblin.shoulder_taps:  {goblin.get('shoulder_taps')}")
    print(f"  goblin.session_priming: {goblin.get('session_priming')}")
    denylist = cfg.get("denylist") or []
    print(f"  denylist entries:      {len(denylist)}")
    print()

    aw_ok = status["activitywatch_reachable"]
    _print_line(aw_ok, "ActivityWatch reachable" if aw_ok else "ActivityWatch not reachable")

    pid = status["watcher_pid"]
    if not status["is_windows"]:
        _print_line(True, "media watcher: n/a (Windows-only feature)")
    elif pid:
        _print_line(True, f"media watcher running (pid {pid})")
    else:
        _print_line(False, "media watcher not running")

    job = status["distill_job"]
    if job:
        _print_line(
            job.get("enabled", True),
            f"distiller job present (id={job.get('id')}, schedule={job.get('schedule_display')}, "
            f"{'enabled' if job.get('enabled', True) else 'paused'})",
        )
    else:
        _print_line(False, "distiller job not found -- run `marvi presence setup`")

    print()
    return 0


def _cmd_pause(args) -> int:
    result = pause_presence()
    _print_line(result["ok"], result["message"])
    _print_line(True, "presence.enabled set to false")
    return 0 if result["ok"] else 1


def _cmd_resume(args) -> int:
    result = resume_presence()
    _print_line(result["ok"], result["message"])
    _print_line(True, "presence.enabled set to true")
    return 0 if result["ok"] else 1


def presence_command(args) -> int:
    sub = getattr(args, "presence_command", None) or "status"
    handlers = {
        "setup": _cmd_setup,
        "status": _cmd_status,
        "pause": _cmd_pause,
        "resume": _cmd_resume,
    }
    handler = handlers.get(sub)
    if handler is None:
        print(f"Unknown presence subcommand: {sub}")
        return 1
    return handler(args)


def add_parser(subparsers) -> None:
    """Register `marvi presence` on the given argparse subparsers object."""
    presence_parser = subparsers.add_parser(
        "presence",
        help="Marvi desktop presence: ActivityWatch integration + media watcher",
        description=(
            "Manage Marvi's presence subsystem: probes ActivityWatch, "
            "supervises the optional Windows now-playing watcher, and "
            "creates the nightly presence distiller cron job. Run with no "
            "subcommand for status."
        ),
    )
    presence_sub = presence_parser.add_subparsers(dest="presence_command")

    presence_sub.add_parser(
        "setup",
        help="Probe ActivityWatch, start the media watcher, create the distiller job",
    )
    presence_sub.add_parser(
        "status",
        help="Show ActivityWatch / media watcher / distiller job status",
    )
    presence_sub.add_parser(
        "pause",
        help="Stop the media watcher and set presence.enabled: false",
    )
    presence_sub.add_parser(
        "resume",
        help="Start the media watcher and set presence.enabled: true",
    )

    presence_parser.set_defaults(func=presence_command)
